spring:
  docker:
    compose:
      enabled: false

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:55432/bets}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
    consumer:
      group-id: betservice-local
      properties:
        isolation.level: read_committed
    producer:
      properties:
        acks: all

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

server:
  port: 8080

security:
  jwt:
    secret: ${JWT_SECRET:oVLa[\$^{m(8jktl*<DQI'H"r@zZS}g%U]9,y?EXw4dAn:-F>|hv0esWx;)/PO6`}
    ttl-minutes: ${JWT_TTL_MINUTES:60}